### ISSUE TITLE
上报设备属性失败

### ISSUE THREAD

**Issue by Allforgot** [jpush/JIoT-SDK-Android#2]
上报设备属性返回：
`Client receive message (about report property) from server errcode = 0 code = 6003 seq_no = 40 version = 0 property_size = 0.`

property_size 每次都是 0，平台上没有接收到上报的属性

**Comment by ouyangshengduo** [comment]
我的疑问是，
1.该设备有没有在极光IoT产品界面中添加属性？
2.上报属性时的请求json是什么？
或者提供一下设备的名称

**Comment by ouyangshengduo** [comment]
> 上报设备属性返回：
> `Client receive message (about report property) from server errcode = 0 code = 6003 seq_no = 40 version = 0 property_size = 0.`
> 
> property_size 每次都是 0，平台上没有接收到上报的属性

我的疑问是，
1.该设备有没有在极光IoT产品界面中添加属性？
2.上报属性时的请求json是什么？
或者提供一下设备的名称

**Comment by Allforgot** [comment]
> > 上报设备属性返回：
> > `Client receive message (about report property) from server errcode = 0 code = 6003 seq_no = 40 version = 0 property_size = 0.`
> > property_size 每次都是 0，平台上没有接收到上报的属性
> 
> 我的疑问是，
> 1.该设备有没有在极光IoT产品界面中添加属性？
> 2.上报属性时的请求json是什么？
> 或者提供一下设备的名称

有添加属性的，用 rest api 也能上传成功。设备名称是 device1
demo上把PropertyReportReq的version设置为5、seq_no设置为40，但返回结果显示version是0、seq_no是40

**Comment by ouyangshengduo** [comment]
> > > 上报设备属性返回：
> > > `Client receive message (about report property) from server errcode = 0 code = 6003 seq_no = 40 version = 0 property_size = 0.`
> > > property_size 每次都是 0，平台上没有接收到上报的属性
> > 
> > 
> > 我的疑问是，
> > 1.该设备有没有在极光IoT产品界面中添加属性？
> > 2.上报属性时的请求json是什么？
> > 或者提供一下设备的名称
> 
> 有添加属性的，用 rest api 也能上传成功。设备名称是 device1
> demo上把PropertyReportReq的version设置为5、seq_no设置为40，但返回结果显示version是0、seq_no是40
第一次上报属性version值需要传1，后面也只能+1，不能跳着递增
